# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ToDo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for ToDo
  # UI
  pod 'SnapKit', '~> 5.6.0'
  pod 'Hero', '~> 1.6.2'
  pod 'Hue'

  # UI Components
  pod 'KDCircularProgress'
  pod 'SwipeCellKit'
  pod 'lottie-ios', '~> 3.4.4'
  pod 'SkyFloatingLabelTextField'

  # Network
  pod 'Alamofire'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
