# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'todoey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for todoey

  # UI
  pod 'SnapKit', '~> 5.6.0'
  pod 'Hero', '~> 1.6.2'
  pod 'Hue'
  pod 'lottie-ios'

  # UI Component
  pod 'KDCircularProgress'
  pod 'SwipeCellKit'

  # Networking
  pod 'Alamofire'
  pod 'SwiftyJSON'
end
